### ISSUE TITLE
new smartmach to upstream

### ISSUE THREAD

**Issue by ure** [gtsafas/mailgun.perl#21]
would it be possible to release this to 0.54 on cpan ?

**Comment by keithbro** [comment]
https://github.com/gtsafas/mailgun.perl/commit/9337b23d4acdf477c132a237657c1be78177968b

Uploading to CPAN now

**Comment by keithbro** [comment]
It's released now http://search.cpan.org/~keithbro/WWW-Mailgun-0.54/
