### ISSUE TITLE
Support for multiple tags

### ISSUE THREAD

**Issue by kotimaakinnu** [gtsafas/mailgun.perl#9]
https://documentation.mailgun.com/user_manual.html#tagging

Mailgun supports up to 3 tags per email. Each tag is sent as a separate post-param. But since the send-method takes a hashref as input, only one tag can be added. Possible fix would to add a special key `tags` with arrayref as value, which then gets unpacked into separate post-params. Pretty much exactly like `attachments` in version 0.5

    $mg->send({
       subject => 'Your account for xyz',
       ....
       tags => ['adminmail', 'newuser']
    });

**Comment by gtsafas** [comment]
@kotimaakinnu @keithbro think this can be closed now. I merged in the changes @keithbro had
